---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi